const axios = require("axios");

module.exports = {
  config: {
    name: "fbcreate",
    aliases: ["createfb"],
    version: "1.5",
    author: "Jonnel",
    countDown: 5,
    role: 0,
    shortDescription: {
      en: "Create fake Facebook account"
    },
    longDescription: {
      en: "Generate a Facebook account using Haji Mix API with style"
    },
    category: "utility",
    guide: {
      en: "{pn}"
    }
  },

  execute: async function ({ api, event }) {
    const header = `
🟢⚪🔴  🤖 𝗙𝗔𝗞𝗘 𝗙𝗔𝗖𝗘𝗕𝗢𝗢𝗞 𝗔𝗖𝗖𝗢𝗨𝗡𝗧 𝗕𝗬 𝗝𝗢𝗡𝗡𝗘𝗟 🤖  🟢⚪🔴
`;

    try {
      const url = "https://haji-mix-api.gleeze.com/api/fbcreate?amount=1&email=jonnelsoriano143%40gmail.com&api_key=8672951c715e5945e70b9da2663e3bbc2a3e7c678738a094057e3117c3a699ea";
      const res = await axios.get(url);

      const account = res.data?.data?.[0]?.account;

      if (!account) {
        console.log("❌ API returned:", res.data);
        return api.sendMessage(header + "\n❌ Failed to create Facebook account. Check API or response format.", event.threadID);
      }

      const msg = `
${header}

✅ 𝗙𝗮𝗸𝗲 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 𝗖𝗿𝗲𝗮𝘁𝗲𝗱 𝗦𝘂𝗰𝗰𝗲𝘀𝘀𝗳𝘂𝗹𝗹𝘆 ✅

👤 Name: ${account.name}
📧 Email: ${account.email}
🔐 Password: ${account.password ? '--- ' + account.password + ' ---' : "N/A"}
🎂 Birthday: ${account.birthday || "N/A"}
🚻 Gender: ${account.gender || "N/A"}
📩 Note: ${account.message || "N/A"}

💡 Generated by Nobita Bot
`;

      return api.sendMessage(msg, event.threadID);
    } catch (error) {
      console.error("[fbcreate.js] Error:", error.message);
      return api.sendMessage("❌ Error creating Facebook account. Try again later.", event.threadID);
    }
  }
};